#!/bin/bash

branch="main"
commit_message="misc: update"

args=()
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -b)
            branch="$2"
            shift 2
            ;;
        -m)
            commit_message=$(printf "$2")
            shift 2
            ;;
        -c)
            if [[ "$2" != *[!0-9]* ]]; then
                clone_depth="$2"
                shift 2
            else
                printf "[+] Invalid depth value.\n"
                exit 1
            fi
            ;;
        -f)
            force_push=true
            shift
            ;;
        -l)
            fetch_latest=true
            shift
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

if [[ "${#args[@]}" -lt 2 ]]; then
    printf "\n[+] Usage: [-b <branch>] [-m <message>] [-c <depth>] [-f] [-l] <github_username> <github_email> [<github_token>] [<repository_owner/repository_name>]\n\n"
    exit 1
fi

gh_username="${args[0]}"
gh_email="${args[1]}"
gh_token="${args[2]}"
repository="${args[3]:-$gh_username/${PWD##*/}}"
repository_url="https://${gh_token:+x-access-token:$gh_token@}github.com/$repository"

if ! command -v git 1>/dev/null; then
    printf "\n[+] Git is not installed.\n+ Installing Git...\n\n"
    apt-get install -y --no-install-recommends git
fi

git config set --global safe.directory "*"

if [[ -n "$clone_depth" ]]; then
    git clone -b "$branch" --depth "$clone_depth" --filter=blob:none "$repository_url"
    exit 0
fi

[[ ! -d .git ]] && git init -q
git config set --local user.name "$gh_username"
git config set --local user.email "$gh_email"

git remote set-url origin "$repository_url" 2>/dev/null || git remote add origin "$repository_url"
[[ -v fetch_latest ]] && git fetch --depth 1 --filter=blob:none origin "$branch" || false && git reset FETCH_HEAD

git add -- .
git status
read -n 1 -p "% Press [Enter] to continue."

git commit -m "$commit_message" --allow-empty || exit 0
git push ${force_push:+-f} origin "HEAD:$branch" || git reset "origin/$branch"