name: Checksum
run-name: Checksum (${{ inputs.delete-specific-abis && 'Delete Specific ABIs' }})
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
      cookies:
        description: Cookies
      delete-specific-abis:
        description: Delete specific ABIs
        type: boolean

jobs:
  checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: printf "%s\n" "FILENAME=$(curl -sSLOJ -w "%{filename_effective}" -b "${{ inputs.cookies }}" "${{ inputs.url }}")" >> "$GITHUB_ENV"

      - name: Checksum
        run: |
          if [[ "${{ inputs.delete-specific-abis }}" == "true" ]]; then
            zip -q -d "$FILENAME" "lib/armeabi-v7a/*" "lib/x86/*" "lib/x86_64/*" "META-INF/*"
          fi

          cksum -a sha256 "$FILENAME"

      - name: Archive
        run: 7z a -m0=lzma2 -mx=9 archive.7z .

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: archive.7z
