name: Checksum
run-name: Checksum (${{ inputs.strip-abi && 'Strip ABI' || 'No Strip ABI' }})
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
      cookies:
        description: Cookies
      strip-abi:
        description: Strip ABI
        type: boolean

jobs:
  checksum:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download
        run: printf "%s\n" "FILENAME=$(curl -sSLOJ -w "%{filename_effective}" -b "${{ inputs.cookies }}" "${{ inputs.url }}")" >> "$GITHUB_ENV"

      - name: Checksum
        run: |
          if [[ "${{ inputs.strip-abi }}" == "true" ]]; then
            zip -q -d "$FILENAME" "lib/armeabi-v7a/*" "lib/x86/*" "lib/x86_64/*" "META-INF/*"
          fi

          cksum -a sha256 "$FILENAME"
          7z a -m0=lzma2 -mx=9 "$FILENAME.7z" "$FILENAME"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.workflow }}
          name: Artifacts
          files: ${{ env.FILENAME }}.7z
