name: Extract Boot Image
on:
  workflow_dispatch:
    inputs:
     fastboot-rom-url:
        description: Fastboot ROM URL
        required: true

jobs:
  extract-boot-image:
    runs-on: ubuntu-latest
    steps:
      - name: Extract boot image
        run: curl -sSL "${{ inputs.fastboot-rom-url }}" | tar -xz -f - --occurrence --wildcards "*/images/boot.img"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.run_id }}
          name: Artifacts
          files: "*/images/boot.img"
